version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: easyflight-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: easyflight_db
      MYSQL_USER: easyflight_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data:/opt/keycloak/data
    command: start-dev

volumes:
  mysql_data:
  keycloak_data:
